spring.application.name=database.test
spring.h2.console.enabled=true
spring.h2.console.path=/db
spring.datasource.initialize=true

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.userName=admin
spring.datasource.password=331331mama
